### ISSUE TITLE
remove offline note from docset

### ISSUE THREAD

**Issue by shaunlebron** [cljsinfo/cljs-api-docs#104]

**Comment by bilekt3** [comment]
@shaunlebron Is there any way how to generate actual docset for DASH? Thanks for help.

**Comment by shaunlebron** [comment]
Sorry, it's broken right now.  I'm breaking the old stuff as I move to the new.

For now, you can `ctrl+f` this preview page to search for things:
http://cljsinfo.github.io/ref/

**Comment by bilekt3** [comment]
Thanks for info. New site is perfect for me Dash version will be nice ➕.

**Comment by shaunlebron** [comment]
@bilekt3 changed URL to http://cljs.github.io/api
