### ISSUE TITLE
versioned cljsdoc fields

### ISSUE THREAD

**Issue by shaunlebron** [cljsinfo/cljs-api-docs#116]
I was writing about the [lack of cljsdoc versioning](https://github.com/cljsinfo/cljs-api-docs/wiki/cljsdoc-files#different-versions) and realized that when symbols are removed, I either want to:

- state the reasons why (e.g. offenders `cljs.core/format` and `cljs.core/printf`), or...
- show where they moved to (`cljs.core/try` -> `special/try` and others at #115).

I think a solution to both these problems is to provide version tags to section titles (Description and a new section Moved, respectively). I think this also solves some of the lingering questions of what we might do if more things start changing.

```
===== Description
this description applies from the very beginning

===== Description (0.0-1533)
this description applies at and after 0.0-1533

===== Description (0.0-3011)
this description applies at and after 0.0-3011
```

This should allow us to change fields at certain versions, so we can change:

- description (if something changes)
- signature (if updated for new description)
- examples (if this or _dependent_ symbols require updated example code)
- moved (if this symbol moves to another, see #115)

Implementation:

- the output of a parsed and transformed cljsdoc should be a sparse map of version->cljsdoc-fields
- fields present in one version should be present in all future versions until shadowed
- we need a function to retrieve the correct cljsdoc-fields for a given version by searching for the closest parent version key

```clj
{"0.0-927" { ... cljsdoc fields for this version ...}
 "0.0-1533" { ... cljsdoc fields for this version ...}
 ...}
```

**Comment by shaunlebron** [comment]
@oakmac can you review?

**Comment by oakmac** [comment]
This feels like a bit much to me.

The original intent of the .cljsdoc files was to have a simple way to write and manage the doc files using existing tools. At some point the complexity increases where we should probably be using EDN directly, but hopefully we can avoid that for a while.

Basically you're introducing the concept of time into the doc files. I think it's fine for the doc files to just track against CLJS versions as it changes over time. How much value will there be in leaving an "old" description in a file 2 or 3 years after it's been changed? Maybe track these changes in a separate changelog-type format between versions? How many of these changes will there be over time? Seems like it would clutter the docs and be better handled just by using git.

**Comment by shaunlebron** [comment]
I don't agree about ever using EDN directly, mainly because of whitespace and escaped markdown in strings.

I thought the git thing would be okay, but would involve correlating our cljsdoc history with the cljs API history, and would add some complexity to the docs builder to poll its own history.  would also imply that previous doc versions become frozen and uncorrectable.

I think the deciding factor between having multiple or a single cljsdoc file for multiple versions of the symbol is the frequency and types of changes.  Concretely, the only changes I've seen worth documenting so far are removals and renames; none have been added back so far.  And there was a rare change in the arity of a function in the compiler API which broke some third-party REPLs.

So, after four years and 123 versions of existing api history, a cljsdoc file will have at most one extra version, that I'm aware of.

**Comment by oakmac** [comment]
My comment about EDN was just to recognize that the cljsdoc files are structured data. Right now, that data format is relatively simple, as it increases in complexity at some point you're just re-inventing a serializable data format like EDN or JSON. One of the goals is to keep the files as simple as possible.

I think having `===== Moved` or `===== Renamed` sections is fine. Likely that gets added once and then just remains unchanged.

I was mostly concerned about having N number of Description sections that are all slightly different and clutter the file over time. If you don't think this will happen often it's probably not the worst idea ;)
