### ISSUE TITLE
aget is not to be used on objects

### ISSUE THREAD

**Issue by pkobrien** [cljsinfo/cljs-api-docs#128]
At least that's what I got out of a discussion with David Nolen. So the docs and examples here need to be changed and it should probably be pointed out that using aget on anything but an array is a bad idea, even if it currently works.

https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core_aget.md

**Comment by swannodette** [comment]
For interacting with objects use the `goog.object` namespace instead.

**Comment by shaunlebron** [comment]
@swannodette If this is a semantic issue, perhaps we should `(def oget aget)`.  Reason being, `goog.object/get` isn't multi-arity, so in reality I just see users opting for the incorrectly function out of convenience.

**Comment by shaunlebron** [comment]
@pkobrien thanks for filing this issue!

**Comment by swannodette** [comment]
@shaunlebron we're not going to add `oget` since `goog.object.getValueByKeys` already does :)

**Comment by pkobrien** [comment]
@shaunlebron You're welcome. :-)

**Comment by pkobrien** [comment]
Something about this doesn't feel right to me. I don't understand what value the Google Closure implementation adds, since all it does is this:
```
goog.object.get = function(obj, key, opt_val) {
  if (key in obj) {
    return obj[key];
  }
  return opt_val;
};
```
Why isn't the advice to simply use `aget` on arrays and `get` on objects? What am I missing?

**Comment by swannodette** [comment]
@pkobrien simple rule - in Clojure `aget` is only for arrays, nothing changes for ClojureScript.

**Comment by pkobrien** [comment]
@swannodette right. And we've been talking about javascript objects. So I think what you're saying is that `aget` and `get` are for accessing cljs types, and if you want to deal directly with plain old js objects you should use goog.object functions. Because that's the design specification of the Clojure/ClojureScript language, and because you're going to tighten up the compiler code in order to improve performance. Am I close? It seems like the host interop issues are more at the surface for ClojureScript developers because it's pretty hard to write a browser app without having to deal with regular js objects, whereas with Clojure you can do a lot without having to deal directly with Java objects.

**Comment by swannodette** [comment]
@pkobrien ok, sorry I misunderstood what you were saying. Here are types and the corresponding accessors you should be using:

`ILookup` - `get` or `get-in`
`js/Array` - `aget`
`js/Object` - `goog.object/get` or `goog.object/getValueByKeys`

Use the right function for the right type.

**Comment by pkobrien** [comment]
@swannodette We are on the same page now, thanks. :-)

**Comment by shaunlebron** [comment]
updated [`aget`] and [`aset`], but there is no multi-arity version of [`goog.object/set`] I can find.

I'm still voting for `oset` and `oget` aliases due to UX.  including goog.object isn't a big deal, but js property access should be completely painless core feature, right?

[`aget`]:https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core_aget.md
[`aset`]:https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core_aset.md
[`goog.object/set`]:http://google.github.io/closure-library/api/namespace_goog_object.html#set

**Comment by swannodette** [comment]
We're not going to add `oset`. `goog.object` is comprehensive enough. Multi-arity set just isn't that important given merging anyway.
